version: '3.7'

services:
  app_los:
    build:
      context: .
      dockerfile: ./.docker/Dockerfile
    container_name: app_los
    restart: unless-stopped
    tty: true
    working_dir: /var/www
    extra_hosts:
        - "host.docker.internal:host-gateway"
    environment:
      PHP_IDE_CONFIG: 'serverName=Docker'
    volumes:
      - ./:/var/www
      - ./.docker/nginx/conf.d/:/etc/nginx/conf.d/
      - ./.docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
      - ./.docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    networks:
      - app-los-network
    depends_on:
      - db_los
      - redis_los

  #Nginx Service
  webserver_los:
    image: nginx:1.21 # https://hub.docker.com/_/nginx
    container_name: webserver_los
    restart: unless-stopped
    tty: true
    ports:
        - '80:80'
        - '443:443'
        - '8443:8443'
    volumes:
      - ./ssl/:/etc/nginx/certs
      - ./:/var/www
      - ./.docker/nginx/conf.d/:/etc/nginx/conf.d/
      - ./storage/logs/nginx/:/var/log/nginx/
    command: nginx -g "daemon off;"
    environment:
      VIRTUAL_HOST: los.local.ua
      VIRTUAL_PORT: 443
      NGINX_ENTRYPOINT_QUIET_LOGS: 1
    networks:
      - app-los-network
    depends_on:
      - app_los

  # MySQL Service
  # https://hub.docker.com/_/mysql
  db_los:
    image: mysql:5.7
    container_name: db_los
    restart: unless-stopped
    tty: true
    ulimits: # for linux to prevent huge memory usage
        nofile:
          soft: 10000
          hard: 10000
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: 'los_local'
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: los_local
      MYSQL_PASSWORD: los_local
    volumes:
      - ./storage/db_data:/var/lib/mysql
      - ./.docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - app-los-network

  # https://hub.docker.com/r/phpmyadmin/phpmyadmin
  php_my_admin_los:
    image: phpmyadmin/phpmyadmin:5.1.0
    container_name: php_my_admin_los
    restart: unless-stopped
    tty: true
    ports:
      - "8080:80"
    environment:
      PMA_HOST : "db_los"
      PMA_USER : "root"
      PMA_PASSWORD : "root"
      PMA_ARBITRARY: 1
      UPLOAD_LIMIT: 30M
    volumes:
      - ./.docker/mysql/config.phpmyadmin.inc.php:/etc/phpmyadmin/config.user.inc.php
      - ./.docker/mysql/darkwolf:/var/www/html/themes/darkwolf
    networks:
      - app-los-network
    depends_on:
      - db_los

  php_redis_admin_los:
    image: erikdubbelboer/phpredisadmin # https://hub.docker.com/r/erikdubbelboer/phpredisadmin
    container_name: php_redis_admin_los
    restart: unless-stopped
    environment:
      REDIS_1_HOST: redis_los
      REDIS_1_NAME: DockerRedis
      REDIS_1_PORT: 6379
    ports:
      - "8082:80"
    networks:
      - app-los-network
    depends_on:
      - redis_los

  redis_los:
    image: redis:3.2 # https://hub.docker.com/_/redis
    container_name: redis_los
    restart: unless-stopped
    command: ["redis-server", "--bind", "0.0.0.0", "--port", "6379"]
    volumes:
      - ./storage/redis-data:/var/lib/redis
      - ./.docker/redis/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
    networks:
      - app-los-network


#Docker Networks
networks:
  app-los-network:
    name: los
    driver: bridge
